name: Publish to GitHub Packages

on:
	push:
		branches: [ main ]
	workflow_dispatch:

jobs:
	publish:
		runs-on: ubuntu-latest
		permissions:
			contents: read
			packages: write
		steps:
			- uses: actions/checkout@v3
			
			- name: Setup Node.js
				uses: actions/setup-node@v3
				with:
					node-version: '16.x'
					registry-url: 'https://npm.pkg.github.com'
					
			- name: Configure npm
				run: |
					echo "@zerrodevs:registry=https://npm.pkg.github.com" >> .npmrc
					echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
			
			- name: Install dependencies
				run: npm install
			
			- name: Publish to GitHub Packages
				run: npm publish --access public
				env:
					NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
					NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}